name: "Get Filtered branches"
description: "Github Action filter branches and get it in a string comma separated on output"
branding:
  icon: git-pull-request
  color: blue
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true  
  TARGET_BRANCH_STARTS_WITH:
    description: "Branch to make the pull-request against"
    required: true
outputs:
  LIST:
    description: "matching branches list, separated by comma"
runs:
  using: "node12"
  main: "index.js"
